
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flappy-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flappy
  template:
    metadata:
      labels:
        app: flappy
    spec:
      containers:
      - name: flappy
        image: IMAGE_PLACEHOLDER
        ports:
        - containerPort: 80
