
apiVersion: apps/v1
kind: Deployment
metadata:
  name: snake-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snake
  template:
    metadata:
      labels:
        app: snake
    spec:
      containers:
      - name: snake
        image: IMAGE_PLACEHOLDER
        ports:
        - containerPort: 80
